/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_hippo_sample_j2se_jni_MyJni */

#ifndef _Included_org_hippo_sample_j2se_jni_MyJni
#define _Included_org_hippo_sample_j2se_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hippo_sample_j2se_jni_MyJni
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_hippo_sample_j2se_jni_MyJni_display
  (JNIEnv *, jobject);

/*
 * Class:     org_hippo_sample_j2se_jni_MyJni
 * Method:    sum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_hippo_sample_j2se_jni_MyJni_sum
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
